apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alb-alerts
  namespace: monitoring
spec:
  groups:
  - name: alb.rules
    rules:

    - alert: ALBUnhealthyTargets
      expr: aws_alb_unhealthy_host_count > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "ALB Unhealthy Targets"
        description: "ALB has unhealthy backend targets."
