apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: support-readonly-cluster
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "pods/log", "services", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
